-- BỔ SUNG THÊM 50 CÂU HỎI MỚI CHO TỪNG BỘ (Tổng 200 câu)

-- Category 'fun' (+50 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('fun', '{"en": "If you could instantly speak another language, what would it be?", "vi": "Nếu bạn có thể lập tức nói lưu loát một ngoại ngữ mới, đó sẽ là tiếng gì?"}'),
('fun', '{"en": "What’s the most ridiculous outfit you’ve ever worn in public?", "vi": "Bộ đồ lố bịch nhất bạn từng mặc ra đường là gì?"}'),
('fun', '{"en": "If our pets could talk, what would they say about us?", "vi": "Nếu thú cưng biết nói, bạn nghĩ nó sẽ nói xấu gì về chúng ta?"}'),
('fun', '{"en": "What is a cartoon you still secretly enjoy watching?", "vi": "Có bộ phim hoạt hình nào bạn vẫn lén lút xem dù đã lớn không?"}'),
('fun', '{"en": "If you could only use one emoji for the rest of your life, which one?", "vi": "Nếu chỉ được dùng 1 emoji suốt phần đời còn lại, bạn chọn cái nào?"}'),
('fun', '{"en": "What’s the most useless object you currently own?", "vi": "Món đồ vô dụng nhất bạn đang sở hữu là gì?"}'),
('fun', '{"en": "Have you ever accidentally sent a text to the wrong person?", "vi": "Bạn đã bao giờ gửi nhầm tin nhắn cho ai đó và bị quê chưa? Kể đi."}'),
('fun', '{"en": "If you had a warning label on your forehead, what would it say?", "vi": "Nếu bạn bị dán một nhãn cảnh báo trên trán, nó sẽ ghi chữ gì?"}'),
('fun', '{"en": "What is the worst meal you’ve ever cooked?", "vi": "Món ăn thảm họa nhất mà bạn từng nấu là gì?"}'),
('fun', '{"en": "If you had to change your first name, what would you choose?", "vi": "Nếu phải đổi tên thật của mình, bạn sẽ lấy tên gì?"}'),
('fun', '{"en": "What is a conspiracy theory you actually believe might be true?", "vi": "Thuyết âm mưu điên rồ nào mà bạn lại tin là có thật?"}'),
('fun', '{"en": "If you were a ghost, who would you haunt first?", "vi": "Nếu trở thành hồn ma, bạn sẽ đi hù dọa ai đầu tiên?"}'),
('fun', '{"en": "What is the funniest rumor you have ever heard about yourself?", "vi": "Tin đồn buồn cười nhất bạn từng nghe về bản thân mình là gì?"}'),
('fun', '{"en": "Which fast food chain deserves a Michelin star?", "vi": "Hãng đồ ăn nhanh nào theo bạn xứng đáng được trao sao Michelin?"}'),
('fun', '{"en": "If you could erase one song from existence, what would it be?", "vi": "Nếu bạn có thể xóa xổ hoàn toàn 1 bài hát trên thế giới, đó là bài nào?"}'),
('fun', '{"en": "What is the most embarrassing thing you did to get a crush’s attention?", "vi": "Điều đáng xấu hổ nhất bạn từng làm chỉ để cưa cẩm crush (hồi xưa) là gì?"}'),
('fun', '{"en": "If you were kidnapped by aliens, what would you tell them about Earth?", "vi": "Nếu bị người ngoài hành tinh bắt cóc, bạn sẽ nói gì về Trái Đất?"}'),
('fun', '{"en": "What is a word you always mispronounce or spell wrong?", "vi": "Từ vựng nào mà bạn luôn luôn viết sai chính tả hoặc phát âm nhầm?"}'),
('fun', '{"en": "If you had to compete in the Olympics, what sport would you magically be best at?", "vi": "Nếu phải thi Olympic, bạn ước mình sẽ vô địch môn nào?"}'),
('fun', '{"en": "What’s the worst lie you told your parents as a teenager?", "vi": "Lời nói dối tệ nhất bạn từng ném cho bố mẹ hồi tuổi teen là gì?"}'),
('fun', '{"en": "Would you rather have a pet dinosaur or a pet dragon?", "vi": "Bạn thích nuôi khủng long hay nuôi rồng?"}'),
('fun', '{"en": "If you could make one thing illegal that is currently legal, what?", "vi": "Nếu có quyền biến một việc hợp pháp thành bất hợp pháp, bạn cấm điều gì?"}'),
('fun', '{"en": "What the weirdest thought you’ve had in the shower?", "vi": "Suy nghĩ kỳ quặc nhất bạn từng nảy ra lúc đang tắm là gì?"}'),
('fun', '{"en": "If you had to eat pizza with one topping forever, what is it?", "vi": "Nếu chỉ được ăn pizza với 1 loại topping duy nhất suốt đời, đó là gì?"}'),
('fun', '{"en": "What is the worst superpower someone could realistically have?", "vi": "Siêu năng lực vô dụng/thảm họa nhất mà một siêu nhân có thể có là gì?"}'),
('fun', '{"en": "What animal perfectly captures your current mood?", "vi": "Con vật nào phản ánh đúng nhất trạng thái của bạn ngay lúc này?"}'),
('fun', '{"en": "If you were arrested, what would your friends assume you did?", "vi": "Nếu bạn bị bắt, bạn bè sẽ đoán bạn đã nhúng chàm tội gì?"}'),
('fun', '{"en": "Have you ever laughed so hard you cried in an inappropriate situation?", "vi": "Đã bao giờ bạn cười sặc sụa ở một nơi hoàn toàn nghiêm túc chưa?"}'),
('fun', '{"en": "What’s the weirdest habit you had as a kid?", "vi": "Thói quen kỳ quặc nhất hồi bé của bạn là gì?"}'),
('fun', '{"en": "If you had unlimited money to build a ridiculous room in our house, what is it?", "vi": "Nếu xây một căn phòng điên rồ trong nhà với ngân sách vô hạn, phòng đó để làm gì?"}'),
('fun', '{"en": "What TV commercial annoys you the most?", "vi": "Quảng cáo truyền hình/Youtube nào khiến bạn phát cáu nhất?"}'),
('fun', '{"en": "If you starred in a reality show, what would your tagline be?", "vi": "Nếu đóng chương trình thực tế, câu cửa miệng của bạn sẽ là gì?"}'),
('fun', '{"en": "Have you ever snorted while laughing?", "vi": "Bạn có hay bị "khịt mũi" văng nước bọt lúc cười lớn không?"}'),
('fun', '{"en": "What is the funniest miscommunication we’ve ever had?", "vi": "Lần hai đứa hiểu nhầm ý nhau hài hước nhất là khi nào?"}'),
('fun', '{"en": "If you could only text using GIFs, which GIF describes you best?", "vi": "Nếu chỉ được nhắn tin bằng ảnh GIF, cái GIF nào miêu tả đúng con người bạn nhất?"}'),
('fun', '{"en": "What’s the strangest gift you’ve ever received?", "vi": "Món quà kỳ cục nhất bạn từng nhận được là gì?"}'),
('fun', '{"en": "Would you rather have spaghetti for hair or sweat mayonnaise?", "vi": "Bạn thà có mái tóc làm bằng mì Ý hay mồ hôi chảy ra là sốt Mayonnaise?"}'),
('fun', '{"en": "What is your best impression of me?", "vi": "Thử nhại lại giọng điệu hoặc cử chỉ đặc trưng nhất của mình xem nào!"}'),
('fun', '{"en": "If you could replace handshakes with another greeting culturally, what?", "vi": "Nếu được thay đổi phong tục bắt tay bằng một hành động khác, bạn chọn gì?"}'),
('fun', '{"en": "What’s a trend you judged others for, but ended up following?", "vi": "Trào lưu nào ban đầu bạn chê bai nhưng cuối cùng lại đu theo?"}'),
('fun', '{"en": "What is a food you can never bring yourself to eat?", "vi": "Món đồ ăn nào mà bạn dù chết đói cũng không muốn động đũa?"}'),
('fun', '{"en": "Have you ever talked to yourself in the mirror out loud?", "vi": "Đã bao giờ bạn đứng trước gương và độc thoại lớn tiếng như diễn viên chưa?"}'),
('fun', '{"en": "If you could shrink any animal to pocket-size, what would you choose?", "vi": "Nếu có thể thu nhỏ bất kỳ con vật nào để bỏ túi, bạn sẽ chọn con nào?"}'),
('fun', '{"en": "What movie cliché annoys you the most?", "vi": "Motip tình tiết phim ảnh nào khiến bạn thấy ngán ngẩm/giả trân nhất?"}'),
('fun', '{"en": "If you had to wear one color for a year, what would it be?", "vi": "Nếu bắt buộc mặc 1 màu áo suốt cả năm, đó sẽ là màu gì?"}'),
('fun', '{"en": "What’s the silliest thing you’ve Google-searched recently?", "vi": "Cụm từ ngớ ngẩn nhất bạn vừa tìm kiếm trên Google gần đây là gì?"}'),
('fun', '{"en": "What game (video, board, sports) do you refuse to play with me because I’m too competitive?", "vi": "Trò chơi nào bạn không bao giờ muốn chơi với mình vì sợ cãi lộn/tình cảm sứt mẻ?"}'),
('fun', '{"en": "If you had to be a piece of furniture, what would you be?", "vi": "Nếu bạn bị biến thành đồ nội thất trong nhà, bạn sẽ muốn là món nào?"}'),
('fun', '{"en": "What song lyrics did you sing completely wrong for years?", "vi": "Câu hát nào mà bạn hát sai lời suốt nhiều năm mới nhận ra?"}'),
('fun', '{"en": "If you could temporarily switch lives with a celebrity, who?", "vi": "Nếu đổi mạng cho một người nổi tiếng 1 ngày, bạn chọn sống cuộc sống của ai?"}');

-- Category 'deep' (+50 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('deep', '{"en": "What specific moment made you realize you wanted to commit to me?", "vi": "Khoảnh khắc cụ thể nào kiến bạn nhận ra bạn muốn gắn bó lâu dài với mình?"}'),
('deep', '{"en": "What’s an insecurity of yours that you seldom admit?", "vi": "Một sự tự ti ẩn sâu bên trong mà bạn hiếm khi chịu thừa nhận?"}'),
('deep', '{"en": "When do you feel most misunderstood by the world?", "vi": "Khi nào bạn cảm thấy cả thế giới không ai thấu hiểu mình?"}'),
('deep', '{"en": "What is a flaw in me that you’ve learned to accept?", "vi": "Một điểm khuyết của mình mà bạn đã dần học cách bao dung/chấp nhận?"}'),
('deep', '{"en": "Has there ever been a time when I unintentionally made you feel alone?", "vi": "Đã bao giờ mình vô tình khiến bạn cảm thấy cô đơn trong chính mối quan hệ này chưa?"}'),
('deep', '{"en": "What does feeling ‘safe’ mean to you?", "vi": "Cảm giác “an toàn” đối với bạn mang ý nghĩa thực sự là gì?"}'),
('deep', '{"en": "If our relationship was put to a severe test, what do you think would save us?", "vi": "Nếu tình cảm hai đứa bị thử thách cực độ, bạn nghĩ điều gì sẽ cứu vãn chúng ta?"}'),
('deep', '{"en": "What memory of your childhood brings you the most comfort?", "vi": "Kỷ niệm tuổi thơ nào luôn mang lại cho bạn sự bình yên dạt dào?"}'),
('deep', '{"en": "How have I changed your perspective on love?", "vi": "Mình đã làm thay đổi góc nhìn của bạn về tình yêu như thế nào?"}'),
('deep', '{"en": "What is something hard you had to forgive someone for?", "vi": "Điều gì khó khăn nhất mà bạn từng phải bao dung tha thứ cho ai đó?"}'),
('deep', '{"en": "In what ways do you feel you’ve grown since we met?", "vi": "Bạn cảm thấy bản thân đã trưởng thành ra sao kể từ khi chúng ta quen nhau?"}'),
('deep', '{"en": "What part of your past do you feel most ashamed of?", "vi": "Góc khuất quá khứ nào khiến bạn cảm thấy xấu hổ nhất?"}'),
('deep', '{"en": "What is an unspoken expectation you have in a relationship?", "vi": "Một kỳ vọng ngầm (không nói ra) mà bạn luôn mong chờ ở người yêu?"}'),
('deep', '{"en": "How do you internally handle overwhelming anxiety?", "vi": "Khi bị một nỗi lo lắng nhấn chìm, bạn đối mặt với nó bằng cách nào trong nội tâm?"}'),
('deep', '{"en": "What makes you feel deeply connected to me beyond physical touch?", "vi": "Phía sau những cái chạm, điều gì làm bạn thấy gắn kết sâu sắc nhất với tâm hồn mình?"}'),
('deep', '{"en": "What is a question you’ve always wanted to ask me but been afraid to?", "vi": "Có câu hỏi nào bạn luôn muốn hỏi nhưng lại e dè sợ mất lòng không?"}'),
('deep', '{"en": "When did you last compromise a core belief for someone else?", "vi": "Lần cuối cùng bạn phải hạ thấp giá trị/niềm tin cốt lõi bản thân vì người khác là khi nào?"}'),
('deep', '{"en": "How do you want me to react when you are shutting down emotionally?", "vi": "Khi bạn thu mình lại và khép kín cảm xúc, bạn muốn mình phản ứng ra sao?"}'),
('deep', '{"en": "What are you most grateful for in your life right now?", "vi": "Điều gì khiến bạn cảm thấy biết ơn nhất trong cuộc sống hiện tại?"}'),
('deep', '{"en": "What does a ‘broken heart’ physically feel like to you?", "vi": "Theo bạn, cảm giác ‘thất tình/trái tim tan vỡ’ thật sự đau như thế nào?"}'),
('deep', '{"en": "If you could undo one life choice, what would it be?", "vi": "Nếu được quay ngược thời gian thu hồi 1 quyết định trong đời, đó sẽ là quyết định gì?"}'),
('deep', '{"en": "What is a burden you’ve been carrying entirely on your own?", "vi": "Gánh nặng nào bạn vẫn luôn âm thầm gánh vác một mình?"}'),
('deep', '{"en": "Do you feel like you communicate your sadness well?", "vi": "Bạn có nghĩ mình giỏi diễn đạt hay bộc lộ nỗi buồn của bản thân không?"}'),
('deep', '{"en": "In what specific situation do you feel completely inadequate?", "vi": "Trong hoàn cảnh nào bạn thấy bản thân vô cùng thiếu sót/tự ti?"}'),
('deep', '{"en": "If we broke up tomorrow, what would you miss the absolute most?", "vi": "Nếu chia tay vào lúc này, điều gì ở mình/chúng ta sẽ khiến bạn nhớ nhung nhất?"}'),
('deep', '{"en": "How do you measure a person’s true character?", "vi": "Bạn dùng thước đo nào để đánh giá bản chất thật của một con người?"}'),
('deep', '{"en": "What compliment from me touched your heart the deepest?", "vi": "Lời khen nào từ mình từng làm trái tim bạn rung động mạnh nhất?"}'),
('deep', '{"en": "What do you think is your most toxic trait?", "vi": "Bạn thẳng thắn thừa nhận đặc điểm Toxic (độc hại) nhất của mình là gì?"}'),
('deep', '{"en": "What is a pain you fear to feel again?", "vi": "Nỗi đau nào bạn kinh hãi và không bao giờ muốn trải qua lần thứ hai?"}'),
('deep', '{"en": "How important is vulnerability to you in maintaining our love?", "vi": "Việc hạ cái tôi xuống (vulnerable) quan trọng như thế nào để giữ lửa tình yêu chúng ta?"}'),
('deep', '{"en": "Do you think we resolve unresolved anger well?", "vi": "Bạn thấy chúng ta có xử lý tốt những cơn giận dỗi bị dồn nén không?"}'),
('deep', '{"en": "What did your previous relationship teach you about love?", "vi": "Mối tình cũ (hoặc trước kia) đã dạy cho bạn bài học đắt giá gì về Tình Yêu?"}'),
('deep', '{"en": "How do you distinguish between loving someone and being attached to them?", "vi": "Làm sao để phân biệt giữa Cảm giác Yêu và Cảm giác phụ thuộc (Attached)?"}'),
('deep', '{"en": "When do you feel most like your true, authentic self?", "vi": "Khi nào bạn cảm thấy mình được sống thật với bản ngã gốc rễ của mình nhất?"}'),
('deep', '{"en": "How can I make you feel heard when we disagree?", "vi": "Khi cãi vã, mình phải làm gì để bạn thấy tiếng nói của mình được lắng nghe?"}'),
('deep', '{"en": "Do you think our core life philosophies align?", "vi": "Bạn tin rằng hệ tư tưởng/Triết lý sống của hai đứa có thực sự đồng điệu không?"}'),
('deep', '{"en": "What emotional trauma do you feel you are still healing from?", "vi": "Vết thương lòng/Mảng tối nào trong tâm lý mà bạn vẫn chưa thực sự lành lặn?"}'),
('deep', '{"en": "If you lost everything today, who would you want by your side?", "vi": "Nếu mất tất cả danh vọng, tài sản, bạn muốn ai ở bên cạnh chống đỡ cùng?"}'),
('deep', '{"en": "What is a behavior to me that you appreciate but never mention?", "vi": "Một hành động mình hay làm khiến bạn ấm lòng nhưng bạn chưa bao giờ mở lời khen ngợi?"}'),
('deep', '{"en": "How do you define spiritual connection between two people?", "vi": "Bạn định nghĩa thế nào về “Sự kết nối Tâm hồn” giữa hai con người?"}'),
('deep', '{"en": "What is the biggest sacrifice you’ve made for someone you love?", "vi": "Sự hy sinh lớn lao nhất bạn từng dành cho người mình thương là gì?"}'),
('deep', '{"en": "What rule of society do you fundamentally rebel against?", "vi": "Định kiến xã hội nào bạn cảm thấy căm ghét và luôn muốn phá vỡ?"}'),
('deep', '{"en": "Do you ever feel like you are pretending to be happy?", "vi": "Có khi nào bạn phải gồng mình diễn màn kịch hạnh phúc lúc đang vỡ vụn chưa?"}'),
('deep', '{"en": "If love was a choice every single morning, why do you choose me?", "vi": "Nếu tình yêu là sự lựa chọn mỗi sáng thức dậy, lý do gì bạn vẫn chọn mình?"}'),
('deep', '{"en": "What is an assumption people make about you that is totally false?", "vi": "Điều gì mọi người thường tự soi xét/nhìn nhận sai lầm về bạn?"}'),
('deep', '{"en": "What is the hardest truth you had to accept about yourself?", "vi": "Sự thật phũ phàng nào về bản thân mà bạn từng phải chua xót chấp nhận?"}'),
('deep', '{"en": "Do you tie your self-worth to your achievements?", "vi": "Bạn có đang đánh đồng Giá trị bản thân với Trình độ kiếm tiền / Thành tựu không?"}'),
('deep', '{"en": "If you could see your emotional baggage visually, how heavy is it?", "vi": "Nếu gánh nặng tâm lý có hình khối, bạn vác trên vai vật nặng bao nhiêu kg lúc này?"}'),
('deep', '{"en": "What is something you’ve given up on trying to change about me?", "vi": "Có tính nết nào ở mình mà bạn đã bóp bụng “Thôi đành chịu” không thèm sửa tì vết nữa?"}'),
('deep', '{"en": "What is the most profound lesson you’ve learned from our relationship?", "vi": "Bài học sâu sắc nhất bạn thu được kể từ khi hai chúng ta bước vào thế giới của nhau là gì?"}');

-- Category 'future' (+50 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('future', '{"en": "If we move to another country, what culture would you adapt to best?", "vi": "Nếu chúng ta phải định cư ở nước ngoài, bạn nghĩ mình hợp nhập gia tuỳ tục với văn hóa nào nhất?"}'),
('future', '{"en": "What is a financial habit we need to change before getting married?", "vi": "Thói quen tiêu tiền nào chúng ta phải bỏ ngay lập tức trước khi tiến tới hôn nhân?"}'),
('future', '{"en": "How do you picture our daily routine when we are old and retired?", "vi": "Hoạt động mỗi sáng của hai vợ chồng già khi về hưu sẽ lãng mạn như thế nào?"}'),
('future', '{"en": "What values are non-negotiable for you in raising children?", "vi": "Triết lý nuôi dạy con cái nào đối với bạn là bất di bất dịch, không được thỏa hiệp?"}'),
('future', '{"en": "If I developed a chronic illness, how would it change our life plan?", "vi": "Giả sử mình mắc bệnh nan y mãn tính, kế hoạch cuộc đời chúng ta sẽ ra sao?"}'),
('future', '{"en": "What is one dream you had to give up for adult responsibilities?", "vi": "Ước mơ lớn nào bạn đành gác lại để lo cơm áo gạo tiền?"}'),
('future', '{"en": "Where do you want our ashes scattered when we pass away?", "vi": "Khi rời bỏ trần thế, bạn muốn ném tro cốt của mình về đâu?"}'),
('future', '{"en": "How important is having a large social circle for our family?", "vi": "Gia đình chúng ta sau này có cần kết thân với nhiều bạn bè/hàng xóm không?"}'),
('future', '{"en": "What is a career pivot you’ve secretly been considering?", "vi": "Bạn có đang nung nấu ý định bẻ lái sự nghiệp sang hướng nào khác không?"}'),
('future', '{"en": "If we had a sudden windfall of $5 million, what’s step one?", "vi": "Nếu bỗng dưng ôm cục tiền 120 Tỷ VNĐ từ trên trời rơi xuống, bước đầu tiên chúng ta làm là gì?"}'),
('future', '{"en": "Do you imagine living in the city, suburbs, or countryside in the long run?", "vi": "Bạn thích cuộc sống xô bồ thành thị, vùng ven biển lặng lẽ, hay nông thôn nuôi cá trồng rau?"}'),
('future', '{"en": "What is a tradition from your family you want to break?", "vi": "Hủ tục/Truyền thống khắc nghiệt nào từ gia đình mình mà bạn muốn chấm dứt ở đời chúng ta?"}'),
('future', '{"en": "How will we handle caring for our aging parents?", "vi": "Sau này, trách nhiệm phụng dưỡng nội ngoại thai nghén/già yếu sẽ phân bổ thế nào?"}'),
('future', '{"en": "What is the biggest risk you want us to take together in the next decade?", "vi": "Bến đỗ rủi ro liều lĩnh nhất bạn muốn chúng ta cùng dấn thân trong 10 năm tới là gì?"}'),
('future', '{"en": "If you could fast-forward to one event in our future, what would it be?", "vi": "Nếu có cỗ máy tua nhanh thời gian đến một cột mốc tương lai, bạn khát khao thấy khoảnh khắc nào nhất?"}'),
('future', '{"en": "What does financial freedom realistically mean to you?", "vi": "Với bạn, con số bao nhiêu hoặc lối sống thế nào mới gọi là Tự do Tài chính thực sự?"}'),
('future', '{"en": "How do you want us to handle disagreements when we have kids around?", "vi": "Nếu cãi nhau nảy lửa, chúng ta sẽ cư xử sao để không làm tổn thương tâm lý con trẻ?"}'),
('future', '{"en": "What is a goal you want to achieve independently from our relationship?", "vi": "Mục tiêu cá nhân nào bạn muốn chinh phục một mình, tách biệt khỏi tổ ấm của hai đứa?"}'),
('future', '{"en": "How will we ensure we don’t lose our ‘spark’ after 15 years?", "vi": "15 năm nữa, khi lửa tàn lụi, chúng ta sẽ đốt lại ngọn lửa tình bằng cách gì?"}'),
('future', '{"en": "What is a lifestyle upgrade you’re dreaming of achieving soon?", "vi": "Bạn đang phấn đấu được tận hưởng thêm Đặc quyền sống/Vật chất gì trong tương lai gần?"}'),
('future', '{"en": "If we could open a small business together, what would we sell?", "vi": "Nếu 2 vợ chồng mở quán kinh doanh buôn bán, tiệm của chúng ta bán gì?"}'),
('future', '{"en": "What is one promise you want to make to our future selves?", "vi": "Bạn muốn thề nguyền 1 lời hứa gì gửi tới phiên bản 50 tuổi của chúng mình?"}'),
('future', '{"en": "How much technology do you want our future kids exposed to?", "vi": "Bạn sẽ quy định chuyện tiếp xúc với iPad, mạng xã hội của con cái nghiệt ngã đến mức nào?"}'),
('future', '{"en": "If I passed away unexpectedly, what do you want my legacy to be?", "vi": "Lỡ mình ra đi đột ngột, bạn muốn người khác nhắc về di sản của mình ra sao?"}'),
('future', '{"en": "What’s the most important habit we should build right now for a healthy future?", "vi": "Thói quen sức khỏe/kỹ năng nào cần rèn ngay bây giờ để sau này không ân hận?"}'),
('future', '{"en": "How do you see our travel style changing as we age?", "vi": "Về già, cách chúng ta đi du lịch sẽ khác biệt phượt bụi thời trẻ thế nào?"}'),
('future', '{"en": "What is a milestone you feel pressured by society to hit?", "vi": "Cột mốc nào (ví dụ mua nhà, lấy chồng sớm) mà bạn thấy bị xã hội đẩy áp lực quá lớn?"}'),
('future', '{"en": "Do you want to retire early, or keep working because you love it?", "vi": "Bạn thích cày mồ hôi kiếm tiền nghỉ hưu sớm F.I.R.E, hay muốn làm việc cống hiến tới cạn sức?"}'),
('future', '{"en": "What is something I can do to make you feel more secure about our future?", "vi": "Mình phải hành động gì để bạn an tâm/tin tưởng hơn về tương lai hai đứa?"}'),
('future', '{"en": "If we were forced to live off-grid for a year, would we survive together?", "vi": "Nếu ném 2 đứa vào rừng cắt đứt liên lạc sống tự túc 1 năm, chúng ta có xé xác nhau không?"}'),
('future', '{"en": "What will be our parenting superpower as a team?", "vi": "Sự kết hợp giữa mình và bạn sẽ tạo ra bộ skill Nuôi con bá đạo gì?"}'),
('future', '{"en": "To what extent do you want politics or religion to shape our future household?", "vi": "Tôn giáo, chính trị sẽ hiện diện trong lối sinh hoạt nhà chúng ta nhiều ra sao?"}'),
('future', '{"en": "What is a fear you hold about becoming a parent?", "vi": "Nỗi kinh hoàng lớn nhất của bạn về chuyện trở thành Bố/Mẹ là gì?"}'),
('future', '{"en": "How will we handle a major career failure if it happens?", "vi": "Lỡ 1 trong 2 đứa phá sản/mất nghiệp, chúng ta sẽ gồng gánh cùng nhau thế nào?"}'),
('future', '{"en": "What piece of advice do you hope our children never follow?", "vi": "Câu châm ngôn giáo điều nào mà bạn khuyên con cái tuyệt đối đừng nghe theo?"}'),
('future', '{"en": "How do you want us to celebrate our 50th anniversary?", "vi": "Lễ kỷ niệm chặng đường Đám Cưới Vàng (50 năm) sẽ hoành tráng cỡ nào?"}'),
('future', '{"en": "Do you see yourself prioritizing career over family at any specific stage?", "vi": "Có giai đoạn nào bạn sẽ chọn hi sinh gia đình để tập trung leo thăng sự nghiệp không?"}'),
('future', '{"en": "What is a hobby you hope we are doing together in our 60s?", "vi": "Sở thích già lọm khọm nào mà 60 tuổi hai đứa dắt tay nhau cùng làm?"}'),
('future', '{"en": "If our future home had a secret room, what would be inside?", "vi": "Nếu nhà mình có 1 căn hầm bí mật, bạn sẽ giấu gì trong đó?"}'),
('future', '{"en": "What is a flaw you hope our children do not inherit from us?", "vi": "Cái nết xấu xí nào bạn chắp tay cầu nguyện Gen của mình đừng truyền sang con?"}'),
('future', '{"en": "How do you want to resolve inheritance or will-planning issues in the future?", "vi": "Vấn đề lập Di chúc hoặc tranh chấp tài sản thừa kế gia phả, bạn sẽ quyết gắt thế nào?"}'),
('future', '{"en": "What is the biggest lesson you want to pass down to the next generation?", "vi": "Bài học sinh tử lớn nhất bạn muốn dặn dò truyền lại cho thế hệ sau là gì?"}'),
('future', '{"en": "If we could build a charity foundation, what cause would it support?", "vi": "Có tiền mở Quỹ từ thiện, chúng ta sẽ cứu trợ lãnh vực nào?"}'),
('future', '{"en": "What is the most beautiful thing about growing old with someone?", "vi": "Thứ tuyệt bích lãng mạn nhất trong việc ‘già đi cùng một người’ là gì?"}'),
('future', '{"en": "How do you view physical changes (wrinkles, weight) impacting our future attraction?", "vi": "Nhan sắc tàn phai, béo bự nhăn nheo về già có làm bạn tụt hứng/bớt yêu mình đi không?"}'),
('future', '{"en": "What will be our family’s designated ‘lazy day’ rules?", "vi": "Quy tắc của Ngày Lười Biếng (Chủ Nhật huỷ diệt) nhà mình sẽ bá đạo cỡ nào?"}'),
('future', '{"en": "If we had to downsize our life to a tiny house, what 3 things must stay?", "vi": "Lỡ mạt vận phải chuyển vào hộp carton / phòng trọ siêu hẹp, 3 món đồ gì bắt buộc phải giữ mang theo?"}'),
('future', '{"en": "How do we balance self-care while actively taking care of each other?", "vi": "Giữa chuỗi ngày mệt nhoài chăm sóc nhau, làm sao để giữ góc thanh xuân riêng tư cho bản thân?"}'),
('future', '{"en": "What would completely destroy our shared vision for the future?", "vi": "Cơn lốc nào đủ sức đánh sập và tàn phá mọi kế hoạch tương lai mà 2 đứa vun đắp?"}'),
('future', '{"en": "What excites you the absolute most when you look at our future timeline?", "vi": "Nếu vẽ ra dòng timeline 50 năm tới, vạch đích nào làm bạn phấn khích điên cuồng nhất?"}');

-- Category 'spicy' (+50 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('spicy', '{"en": "What is your biggest unspoken bedroom fantasy involving me?", "vi": "Mộng tưởng thầm kín nhất trên giường mà bạn muốn làm với mình nhưng chưa chịu nói?"}'),
('spicy', '{"en": "Have you ever fantasized about us in a public setting? Where?", "vi": "Từng tò mò muốn làm chuyện ấy ở một không gian công cộng nào chưa? (Đừng chối)"}'),
('spicy', '{"en": "What outfit of mine instantly makes you weak in the knees?", "vi": "Bộ đồ nào của mình có sức sát thương mạnh nhất làm bạn rụng rời tay chân?"}'),
('spicy', '{"en": "Dare: Send me a risky photo right now, or kiss my neck for 10 seconds.", "vi": "Thử thách: Gửi 1 tấm ảnh hư hỏng cho mình ngay & luôn, hoặc hôn vào cổ mình đủ 10 giây!"}'),
('spicy', '{"en": "What is a specific touch or caress that always turns you on?", "vi": "Điểm nhạy cảm nào chỉ cần chạm nhẹ là bạn tự động tan chảy?"}'),
('spicy', '{"en": "Truth: Have you ever faked being asleep to avoid intimacy?", "vi": "Thú nhận đi: Có bao giờ đóng kịch giả vờ ngủ say ngáy o o để trốn hiệp trả bài chưa?"}'),
('spicy', '{"en": "What was the best intimate moment we’ve shared so far?", "vi": "Hiệp ân ái/khoảnh khắc cuốn hút xôi thịt nào từ trước đến nay làm bạn nhớ nhung day dứt nhất?"}'),
('spicy', '{"en": "How do you feel about dirty talk, and what is your favorite thing to hear?", "vi": "Bạn có ghiền Dirty talk không? Lời lả lơi thì thầm câu gì sẽ làm bạn kích thích tột độ?"}'),
('spicy', '{"en": "Dare: Blindfold me and tease me for one minute without crossing the limit.", "vi": "Thử thách: Bịt mắt mình lại, và mơn trớn 1 phút (không được đi quá giới hạn). Bắt đầu!"}'),
('spicy', '{"en": "What is a kink you used to judge but now find intriguing?", "vi": "Sở thích hư hỏng Kink (Bạo dâm/Trói/..) nào bạn từng chê bai khinh bỉ mà giờ lại tò mò muốn thử?"}'),
('spicy', '{"en": "Truth: What is the dirtiest dream you’ve ever had about me?", "vi": "Sự thật: Giấc mơ mộng tinh/hư hỏng nhất bạn từng mơ về cơ thể mình diễn biến ra sao?"}'),
('spicy', '{"en": "If you could pick one ‘roleplay’ scenario for tonight, what is the script?", "vi": "Nếu tối nay bắt buộc chơi Roleplay (Nhập vai y tá / Cô giáo / Kẻ bắt cóc..), kịch bản của bạn là gì?"}'),
('spicy', '{"en": "Are you more of a dominant or submissive soul in the bedroom?", "vi": "Rũ bỏ hình tượng, trên giường bạn là kẻ chiếm thế thượng phong (Dom) hay phục tùng (Sub)?"}'),
('spicy', '{"en": "What is your favorite time of day to be intimate?", "vi": "Giờ phút hoàng đạo nào trong ngày khiến bạn rạo rực muốn yêu đương xôi thịt nhất?"}'),
('spicy', '{"en": "Dare: Describe my body to me using only food metaphors.", "vi": "Thử thách: Bằng những từ ngữ miêu tả thức ăn, hãy tả lại cơ thể/đường cong của mình đi!"}'),
('spicy', '{"en": "What is something you wish I would do more aggressively?", "vi": "Điều gì bạn khát khao mình bạo lực, cắn xé hoang dại hơn một chút?"}'),
('spicy', '{"en": "Do you enjoy the build-up and teasing more, or the actual act?", "vi": "Bạn thích màn dạo đầu mơn trớn trêu ngươi (teasing) dài, hay thích quất luôn vào lề chính hơn?"}'),
('spicy', '{"en": "Truth: Have you ever used toys by yourself while thinking of me?", "vi": "Sự thật: Có lúc nào ở một mình, bạn dùng công cụ/toy và tưởng tượng tới khuôn mặt mình chưa?"}'),
('spicy', '{"en": "If we were forced to get caught making out by one person, who would it be?", "vi": "Lỡ đen đủi bị bắt quả tang lúc đang cháy hết mình, bạn mặt dày thà để người nào nhìn thấy nhất?"}'),
('spicy', '{"en": "What is a highly sensitive spot on your body most people wouldn’t guess?", "vi": "Huyệt đạo siêu nhạy cảm trên người bạn mà đụng vào là giật điện (nhưng chả ai ngờ tới) là điểm nào?"}'),
('spicy', '{"en": "Dare: Trace a letter on my thigh using your tongue and make me guess it.", "vi": "Thử thách: Dùng lưỡi vẽ 1 chữ cái lên đùi mình, nếu đoán sai thì chịu phạt!"}'),
('spicy', '{"en": "How do you feel about recording ourselves for our own archive?", "vi": "Ý kiến thành thực của bạn về việc lưu giữ tài liệu Mật/Video X của hai đứa ở trong két sắt riêng?"}'),
('spicy', '{"en": "What is the longest you could realistically go without being physically intimate with me?", "vi": "Bạn nghĩ sức chịu đựng nhịn dục (không đụng chạm/skinship) của bạn tối đa được bao lâu?"}'),
('spicy', '{"en": "Truth: What physical feature of someone else caught your eye recently before you remembered me?", "vi": "Sự thật đen tối: Lần gần nhất ánh mắt bạn lỡ tia phải 3 vòng bốc lửa (hoặc body sáu múi) của người lạ mướt mải ngoài đường là khi nào?"}'),
('spicy', '{"en": "Do you prefer it pitch black or with the lights brightly on?", "vi": "Tắt đèn tối thui mò mẫm hay bật đèn pha sáng trưng để nhìn rõ đối phương?"}'),
('spicy', '{"en": "Dare: Take my hand and place it on your favorite part of yourself.", "vi": "Thử thách: Tự tin nắm lấy bàn tay mình, và đặt vào điểm quyến rũ chết người nhất trên cơ thể bạn xem nào."}'),
('spicy', '{"en": "What is the most unexpected thing that totally turns you on?", "vi": "Hành động vô thức ngớ ngẩn nào của mình mà dưới góc nhìn của bạn lại bệ vệ, Sexy đến lạ lùng?"}'),
('spicy', '{"en": "Are you loud or do you prefer to muffle your sounds?", "vi": "Hệ hú hét sảng khoái hay cắn răng gặm gối giữ im lặng?"}'),
('spicy', '{"en": "Truth: What is your secret opinion on watching adult entertainment together?", "vi": "Đánh giá thẳng thắn về ý tưởng hai đứa cùng ngồi xem chung Adult Video (18+) lấy cảm hứng?"}'),
('spicy', '{"en": "What is something I wear that you secretly want to rip off?", "vi": "Một thứ phụ kiện / áo quần mình hay mặc khiến bạn nhìn chỉ muốn xé thành cám lao vào?"}'),
('spicy', '{"en": "Dare: Give me a lap dance for exactly one song, right now.", "vi": "Thử thách bốc lửa: Trói / ngồi lên chân mình, và khiêu vũ (Lap dance) cho tới khi hết 1 bài nhạc ngay lập tức."}'),
('spicy', '{"en": "How important is eye contact to you during the most intense moments?", "vi": "Lúc nồng nàn cao trào căng cực, ánh mắt giao nhau nhìn xuyên thẳng linh hồn quan trọng cỡ nào đối với bạn?"}'),
('spicy', '{"en": "What is your stance on sharing intimate photos while we are apart?", "vi": "Đi công tác xa / Xa nhà dài ngày, luật lệ về việc trao đổi hình mát mẻ Sexting của chúng ta nên thế nào?"}'),
('spicy', '{"en": "Truth: Have you ever been turned on in an inappropriate setting, like a meeting?", "vi": "Sự thật: Kể lại lần bạn bị lên cơn rạo rực lạc lối ở 1 nơi hoang mang nhất (Đi họp, trên bàn nhậu, trong phòng học)?"}'),
('spicy', '{"en": "If my body was a landscape, what would be your favorite terrain to explore?", "vi": "Ví von văn vẻ, nếu cơ thể mình là một thung lũng, nơi nào làm bạn muốn rúc sâu cắm trại nhất?"}'),
('spicy', '{"en": "Dare: Read a romantic/spicy message out loud in the sexiest voice you can muster.", "vi": "Thử thách: Tìm 1 đoạn văn dâm thư / gợi cảm nhất và đọc lớn tiếng bằng tone giọng khao khát chảy nước xem nào."}'),
('spicy', '{"en": "What do I do that makes you feel hopelessly desired?", "vi": "Hành động chiếm hữu / chiếm đoạt nào của mình làm cho bạn thấy bản thân là báu vật không thể chối từ?"}'),
('spicy', '{"en": "How do you feel about trying completely new locations around the house?", "vi": "Quan điểm của bạn về bộ môn trải chiếu ở nhà bếp, rải hoa hồng ở bồn tắm, sô pha phòng khách?"}'),
('spicy', '{"en": "Truth: What is your wildest fantasy involving food or temperature constraints?", "vi": "Có đam mê xài Đá lạnh, nến ấm, siro sô cô la hay kem tươi làm đạo cụ kích thích không?"}'),
('spicy', '{"en": "What is the sexiest non-sexual act a partner could perform for you?", "vi": "Hành động phi-tình-dục (như nấu cơm cởi trần, cột tóc lúc lau nhà...) nào lại sexy chết người trong đầu bạn?"}'),
('spicy', '{"en": "Dare: Kiss me wherever you want, but you can only use your teeth.", "vi": "Thử thách cực bạo: Hôn đâu tuỳ thích, nhưng nghiêm cấm dùng môi, chỉ được cạ nhẹ bằng... Hàm răng!"}'),
('spicy', '{"en": "How do you feel about leaving marks (hickeys/scratches)?", "vi": "Nghiện bộ môn đánh dấu lãnh thổ cào cấu rướm máu (BDSM nhẹ), trồng dâu hickey hay đam mê giữ gìn làn da không tì vết?"}'),
('spicy', '{"en": "What is your biggest fear regarding our intimate life fading?", "vi": "Cơn ác mộng nào đáng sợ nhất khi nghĩ về tương lai chuyện mền mùng của 2 vợ chồng bị lạnh nhạt, chán ngấy?"}'),
('spicy', '{"en": "Truth: Have you ever felt jealous of someone else’s intimacy stories?", "vi": "Ghen tị đỏ mắt: Từng nghe podcast mười tám cộng hay nghe con bạn thân kể vụ giường chiếu nhà nó mà thấy nuối tiếc thèm thuồng chưa?"}'),
('spicy', '{"en": "If we had one night away in a luxury hotel with zero interruptions, what’s the priority?", "vi": "Tổng biên đạo 1 đêm tẩu thoát trăng mật tại ks 5 sao: Bạn sẽ ưu tiên bạo kích cỡ nào?"}'),
('spicy', '{"en": "Dare: Whisper what you want me to do to you later tonight in my ear.", "vi": "Thử thách: 10 giây ghé sát lỗ tai, thì thầm vạch trần âm mưu đen tối bạn định làm với mình đêm nay."}'),
('spicy', '{"en": "What is your take on sensory deprivation (using blindfolds, tying up)?", "vi": "Suy nghĩ về trò chơi bịt mắt, trói nhẹ 2 tay đẩy cảm giác thăng hoa mất kiểm soát lên đỉnh điểm?"}'),
('spicy', '{"en": "Do you like taking the lead, or being completely taken care of and ordered around?", "vi": "Thích cầm trịch / Ra lệnh bắt mình quỳ rạp, hay ngoan ngoãn nằm tận hưởng làm con mèo ướt át?"}'),
('spicy', '{"en": "Truth: What is one boundary you possess that secretly you want me to gently push?", "vi": "Sự thật: Một ranh giới ngượng ngùng nào bạn giăng ra, nhưng sâu thẳm lại mong muốn bờ vai mình sẽ mạnh mẽ phá vỡ nó để dắt bạn đi?"}'),
('spicy', '{"en": "If tonight was our very last night of intimacy, how would it play out?", "vi": "Nếu định mệnh buông lời nguyền: Tối nay là hiệp súng cuối cùng được gần gũi nhau, màn càn quét này sẽ đẫm máu ra sao?"}');
