-- Clear older seed if necessary
DELETE FROM public.question_bank WHERE category IN ('fun', 'deep', 'future', 'spicy');

-- Category 'fun' (30 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('fun', '{"en": "If you could teleport us anywhere for dinner tonight, where to?", "vi": "Nếu tối nay mình có thể dịch chuyển tức thời đến bất kỳ đâu ăn tối, bạn chọn nơi nào?"}'),
('fun', '{"en": "What''s your most embarrassing funny memory?", "vi": "Kỷ niệm hài hước bẽ mặt nhất của bạn là gì?"}'),
('fun', '{"en": "If you had to eat one meal for the rest of your life, what would it be?", "vi": "Nếu bạn chỉ được ăn một món suốt đời, đó sẽ là món gì?"}'),
('fun', '{"en": "What''s a weird quirk you have that you secretly love?", "vi": "Một thói quen kỳ quặc nào của bạn mà bạn lại thấy thích?"}'),
('fun', '{"en": "If we were in a zombie apocalypse, what would be your survival role?", "vi": "Nếu có đại dịch zombie, vai trò sinh tồn của bạn sẽ là gì?"}'),
('fun', '{"en": "What is the strangest dream you’ve ever had?", "vi": "Giấc mơ kỳ lạ nhất bạn từng gặp là gì?"}'),
('fun', '{"en": "If you were a superhero, what would be your superpower?", "vi": "Nếu bạn là siêu anh hùng, siêu năng lực của bạn sẽ là gì?"}'),
('fun', '{"en": "What is the funniest movie you have ever seen?", "vi": "Bộ phim hài hước nhất bạn từng xem là gì?"}'),
('fun', '{"en": "If animals could talk, which would be the rudest?", "vi": "Nếu động vật có thể nói chuyện, loài nào sẽ thô lỗ nhất?"}'),
('fun', '{"en": "What song always makes you want to dance?", "vi": "Bài hát nào luôn làm bạn muốn nhảy?"}'),
('fun', '{"en": "What''s the worst haircut you''ve ever had?", "vi": "Kiểu tóc thảm họa nhất bạn từng để là gì?"}'),
('fun', '{"en": "If you won the lottery, what is the very first thing you''d buy?", "vi": "Nếu trúng số, món đồ đầu tiên bạn mua sẽ là gì?"}'),
('fun', '{"en": "What’s your favorite dad joke?", "vi": "Câu chuyện cười nhạt nhẽo yêu thích của bạn là gì?"}'),
('fun', '{"en": "If you could instantly become an expert in something, what would it be?", "vi": "Nếu bạn có thể lập tức trở thành chuyên gia trong lĩnh vực nào đó, đó sẽ là gì?"}'),
('fun', '{"en": "What is your guilty pleasure TV show?", "vi": "Chương trình truyền hình thực tế hoặc rác nào mà bạn lén thích xem?"}'),
('fun', '{"en": "If you were a flavor of ice cream, what would you be?", "vi": "Nếu bạn là một vị kem, bạn sẽ là vị gì?"}'),
('fun', '{"en": "What is the weirdest food combo you enjoy?", "vi": "Sự kết hợp đồ ăn kỳ lạ nào mà bạn lại thấy ngon?"}'),
('fun', '{"en": "What would the title of your autobiography be?", "vi": "Nếu viết tự truyện, bạn sẽ đặt tiêu đề là gì?"}'),
('fun', '{"en": "If our relationship was a sitcom, what would it be called?", "vi": "Nếu mối quan hệ của chúng ta là phim hài dài tập, nó sẽ tên là gì?"}'),
('fun', '{"en": "What is the worst fashion trend you participated in?", "vi": "Trào lưu thời trang tệ nhất bạn từng đu theo là gì?"}'),
('fun', '{"en": "What fictional character do you relate to the most?", "vi": "Bạn thấy mình giống nhân vật hư cấu nào nhất?"}'),
('fun', '{"en": "If you had to sing karaoke right now, what song would you pick?", "vi": "Nếu bị bắt hát karaoke ngay bây giờ, bạn sẽ chọn bài nào?"}'),
('fun', '{"en": "What is the most ridiculous thing you believed as a child?", "vi": "Điều ngớ ngẩn nhất bạn từng tin sái cổ khi còn bé là gì?"}'),
('fun', '{"en": "If you had to live in a video game world, which one?", "vi": "Nếu phải sống trong một thế giới game, bạn chọn game nào?"}'),
('fun', '{"en": "What animal do you think you could beat in a fight?", "vi": "Bạn nghĩ mình có thể đánh thắng được loài vật nào?"}'),
('fun', '{"en": "What is the silliest reason you''ve ever gotten angry at me?", "vi": "Lý do ngớ ngẩn nhất mà bạn từng nảy sinh bực bội với mình là gì?"}'),
('fun', '{"en": "If you could switch bodies with me for one day, what would you do?", "vi": "Nếu đổi cơ thể cho mình một ngày, bạn sẽ làm gì?"}'),
('fun', '{"en": "What’s your useless hidden talent?", "vi": "Tài lẻ vô dụng nhất của bạn là gì?"}'),
('fun', '{"en": "Who would play us in a movie about our lives?", "vi": "Ai sẽ đóng vai hai đứa mình trong bộ phim về chính chúng ta?"}'),
('fun', '{"en": "What is the most random thing you have bought online?", "vi": "Món đồ ngớ ngẩn nhất bạn từng mua trên mạng là gì?"}');

-- Category 'deep' (30 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('deep', '{"en": "What was your first impression of me?", "vi": "Ấn tượng đầu tiên của bạn về mình là gì?"}'),
('deep', '{"en": "What is a secret you''ve never told me?", "vi": "Một bí mật bạn chưa bao giờ kể cho mình nghe?"}'),
('deep', '{"en": "What''s your favorite memory of us?", "vi": "Kỷ niệm bạn thích nhất khi chúng ta bên nhau là gì?"}'),
('deep', '{"en": "How can I support you better when you are stressed?", "vi": "Mình có thể làm gì để ủng hộ bạn tốt hơn lúc bạn căng thẳng?"}'),
('deep', '{"en": "When did you know you fell in love with me?", "vi": "Bạn nhận ra mình có tình cảm từ khoảnh khắc nào?"}'),
('deep', '{"en": "What is your biggest fear?", "vi": "Nỗi sợ lớn nhất của bạn là gì?"}'),
('deep', '{"en": "When do you feel the most vulnerable with me?", "vi": "Khi nào bạn cảm thấy dễ bị tổn thương nhất với mình?"}'),
('deep', '{"en": "What is a childhood memory that shaped who you are today?", "vi": "Kỷ niệm ấu thơ nào định hình nên con người bạn hôm nay?"}'),
('deep', '{"en": "How do you think we handle conflicts in our relationship?", "vi": "Bạn nghĩ hai đứa mình đối mặt với xung đột như thế nào?"}'),
('deep', '{"en": "What do you appreciate most about me?", "vi": "Bạn trân trọng điều gì nhất ở mình?"}'),
('deep', '{"en": "Is there anything you wish I understood better about you?", "vi": "Có điều gì bạn ước mình có thể thấu hiểu hơn về bạn không?"}'),
('deep', '{"en": "What makes you feel most loved?", "vi": "Điều gì khiến bạn cảm thấy được yêu thương nhất?"}'),
('deep', '{"en": "Have you ever doubted our relationship? Why?", "vi": "Bạn có bao giờ nghi ngờ về mối quan hệ này không? Vì sao?"}'),
('deep', '{"en": "What mistake from your past do you regret most?", "vi": "Sai lầm trong quá khứ nào khiến bạn hối hận nhất?"}'),
('deep', '{"en": "What’s one thing you are currently struggling with?", "vi": "Điều gì bạn đang phải chật vật trải qua lúc này?"}'),
('deep', '{"en": "When was the last time you cried and why?", "vi": "Lần cuối cùng bạn khóc là khi nào và tại sao?"}'),
('deep', '{"en": "What is something I do that unknowingly hurts you?", "vi": "Mình có từng làm điều gì vô tình khiến bạn tổn thương không?"}'),
('deep', '{"en": "How has our relationship changed since we first met?", "vi": "Mối quan hệ của chúng ta đã thay đổi thế nào từ lúc mới quen?"}'),
('deep', '{"en": "What is a core value you will never compromise on?", "vi": "Giá trị cốt lõi nào bạn sẽ không bao giờ nhượng bộ?"}'),
('deep', '{"en": "In what ways do you think we are perfectly matched?", "vi": "Ở khía cạnh nào bạn nghĩ hai chúng ta vô cùng hợp nhau?"}'),
('deep', '{"en": "In what ways are we totally different?", "vi": "Và ở điểm nào chúng ta khác biệt hoàn toàn?"}'),
('deep', '{"en": "What part of your personality are you most proud of?", "vi": "Phần tính cách nào của bản thân khiến bạn tự hào nhất?"}'),
('deep', '{"en": "How do you want to be remembered after you pass?", "vi": "Bạn muốn người đời nhớ đến bạn thế nào sau khi qua đời?"}'),
('deep', '{"en": "What is a boundary you have that you feel is rarely respected?", "vi": "Ranh giới cá nhân nào của bạn ít bị người khác tôn trọng?"}'),
('deep', '{"en": "What does forgiveness mean to you?", "vi": "Sự tha thứ có ý nghĩa thế nào đối với bạn?"}'),
('deep', '{"en": "What is something you wish we talked about more often?", "vi": "Bạn ước chúng ta có thể trò chuyện nhiều hơn về chủ đề gì?"}'),
('deep', '{"en": "What makes you feel proud of us as a couple?", "vi": "Điều gì khiến bạn tự hào nhất về tình yêu của hai đứa?"}'),
('deep', '{"en": "If today was my last day alive, what would you tell me?", "vi": "Nếu hôm nay là ngày cuối cùng mình được sống, bạn sẽ nói gì với mình?"}'),
('deep', '{"en": "What''s the hardest lesson life has taught you so far?", "vi": "Bài học đắt giá nhất mà cuộc đời dạy bạn đến giờ là gì?"}'),
('deep', '{"en": "How do you heal when your heart gets broken?", "vi": "Bạn làm cách nào để chữa lành khi trái tim bị vụn vỡ?"}');

-- Category 'future' (30 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('future', '{"en": "Where do you see us in 5 years?", "vi": "Bạn hình dung chúng ta sẽ thế nào trong 5 năm tới?"}'),
('future', '{"en": "What is your biggest career dream right now?", "vi": "Ước mơ sự nghiệp lớn nhất của bạn lúc này là gì?"}'),
('future', '{"en": "How do you imagine our dream house?", "vi": "Ngôi nhà mơ ước của chúng ta trông sẽ ra sao?"}'),
('future', '{"en": "What''s a major milestone you want us to hit together next year?", "vi": "Một cột mốc lớn nào bạn muốn chúng ta cùng đạt được trong năm tới?"}'),
('future', '{"en": "What is one thing you definitely want to teach our future kids?", "vi": "Một điều bạn chắc chắn muốn dạy cho con cái chúng ta sau này?"}'),
('future', '{"en": "How do you envision our retirement?", "vi": "Bạn hình dung tuổi hưu của chúng ta sẽ ra sao?"}'),
('future', '{"en": "What is a country you want to travel to with me?", "vi": "Quốc gia nào bạn muốn cùng mình đi du lịch nhất?"}'),
('future', '{"en": "What financial goals should we prioritize?", "vi": "Mục tiêu tài chính nào nên được chúng ta ưu tiên hàng đầu?"}'),
('future', '{"en": "How do you want to balance family and career?", "vi": "Bạn định cân bằng gia đình và sự nghiệp như thế nào?"}'),
('future', '{"en": "What tradition do you want to start for our family?", "vi": "Truyền thống nào bạn muốn xây dựng riêng cho gia đình nhỏ của mình?"}'),
('future', '{"en": "Where is the ideal location to settle down?", "vi": "Nơi lý tưởng nhất để chúng ta an cư lạc nghiệp là ở đâu?"}'),
('future', '{"en": "What is one fear you have about the future?", "vi": "Một nỗi lo lớn bạn có về tương lai là gì?"}'),
('future', '{"en": "Would you want to run a business together someday?", "vi": "Bạn có muốn sau này hai vợ chồng cùng kinh doanh gì đó không?"}'),
('future', '{"en": "What is a skill you want to learn in the next 3 years?", "vi": "Kỹ năng nào bạn muốn học trong 3 năm tới?"}'),
('future', '{"en": "How do you normally prefer to spend holidays?", "vi": "Bạn thường muốn dùng những kỳ nghỉ dài ngày ra sao?"}'),
('future', '{"en": "What role will our parents play in our married life?", "vi": "Bố mẹ hai bên sẽ có vai trò/can thiệp thế nào trong hôn nhân chúng ta?"}'),
('future', '{"en": "What does a perfect Sunday look like 10 years from now?", "vi": "Một ngày Chủ nhật hoàn hảo sau 10 năm nữa sẽ thế nào?"}'),
('future', '{"en": "What do you think will be our biggest challenge getting married?", "vi": "Bạn nghĩ thử thách lớn nhất nếu chúng ta cưới nhau là gì?"}'),
('future', '{"en": "Do you want pets in our future home?", "vi": "Bạn có muốn có thú cưng trong tổ ấm tương lai không?"}'),
('future', '{"en": "How will we handle our finances? Shared or separate?", "vi": "Chúng ta nên quản lý tiền bạc thế nào? Gộp chung hay độc lập?"}'),
('future', '{"en": "What is one bad habit you want to drop before we get older?", "vi": "Thói quen xấu nào bạn muốn từ bỏ trước khi chúng ta già đi?"}'),
('future', '{"en": "What legacy do you want to leave behind?", "vi": "Khi rời bỏ thế giới, bạn muốn để lại di sản gì?"}'),
('future', '{"en": "How important is religion or spirituality in our future?", "vi": "Tôn giáo hay tín ngưỡng quan trọng thế nào trong tương lai cả hai?"}'),
('future', '{"en": "What is a new hobby we should pick up together?", "vi": "Có sở thích mới nào chúng ta nên tập chơi cùng nhau không?"}'),
('future', '{"en": "If we had unlimited money, how would our lifestyle change?", "vi": "Nếu có vô hạn tiền, phong cách sống của chúng ta sẽ đổi khác ra sao?"}'),
('future', '{"en": "What will we do to keep the romance alive in 20 years?", "vi": "20 năm nữa, chúng ta làm gì để giữ lửa tình yêu?"}'),
('future', '{"en": "How should we split household chores in the future?", "vi": "Chúng ta nên chia sẻ việc nhà thế nào?"}'),
('future', '{"en": "What advice would you give to our future selves?", "vi": "Bạn muốn dặn dò gì với phiên bản tương lai của chính mình?"}'),
('future', '{"en": "What makes you excited about getting older together?", "vi": "Điều gì khiến bạn háo hức khi nghĩ đến cảnh già đi cùng nhau?"}'),
('future', '{"en": "What is your ultimate definition of a successful life?", "vi": "Định nghĩa tột cùng của bạn về một cuộc đời thành công là gì?"}');

-- Category 'spicy' (30 Questions)
INSERT INTO public.question_bank (category, question_text) VALUES 
('spicy', '{"en": "What''s your biggest physical turn-on?", "vi": "Điểm hấp dẫn nhất về mặt cơ thể của người kia là gì?"}'),
('spicy', '{"en": "What is a fantasy you''ve always had?", "vi": "Một mộng tưởng thầm kín mà bạn luôn nghĩ tới?"}'),
('spicy', '{"en": "What was going through your head the first time we kissed?", "vi": "Lần đầu tiên chúng ta hôn nhau, bạn đã nghĩ gì?"}'),
('spicy', '{"en": "Truth or Dare: Tell me something you thought about me but never dared to say.", "vi": "Truth or Dare: Nói một điều bạn từng nghĩ về mình nhưng chưa từng dám nói ra."}'),
('spicy', '{"en": "What is your favorite place to be massaged?", "vi": "Bạn thích được chạm/massage ở vùng nào nhất?"}'),
('spicy', '{"en": "Where is the craziest place you would want to be intimate?", "vi": "Địa điểm điên rồ nhất bạn từng muốn có những cử chỉ thân mật?"}'),
('spicy', '{"en": "What is something I wear that you find incredibly attractive?", "vi": "Món đồ nào trên người mình khiến bạn thấy hút mắt nhất?"}'),
('spicy', '{"en": "What is your biggest turn-off in the bedroom?", "vi": "Điều gì làm bạn dập tắt cảm xúc nhất trong chuyện ấy?"}'),
('spicy', '{"en": "Dare: Kiss me on a spot you’ve never kissed before.", "vi": "Thử thách: Hôn mình ở một chỗ bạn chưa từng chạm môi."}'),
('spicy', '{"en": "What do I do that turns you on without me realizing it?", "vi": "Mình có hay làm điều gì gợi cảm mà bản thân không hề hay biết không?"}'),
('spicy', '{"en": "Have you ever had a dream about me? What happened?", "vi": "Bạn đã bao giờ mơ bậy bạ về mình chưa? Kể đi."}'),
('spicy', '{"en": "What is your favorite intimacy memory with me?", "vi": "Kỷ niệm thân mật nào giữa hai ta khiến bạn ám ảnh thích thú nhất?"}'),
('spicy', '{"en": "How do you like to be initiated?", "vi": "Bạn thích được bắt đầu khơi mào chuyện ấy như thế nào?"}'),
('spicy', '{"en": "What’s a kink or fetish you are curious to explore?", "vi": "Gu hay sở thích ẩn khuất (táo bạo) nào bạn muốn thử?"}'),
('spicy', '{"en": "Dare: Describe your favorite part of my body with eyes closed.", "vi": "Thử thách: Nhắm mắt lại và miêu tả chi tiết đường nét cơ thể bạn thích nhất ở mình."}'),
('spicy', '{"en": "What is something dirty you’ve been wanting to try with me?", "vi": "Một điều "hư hỏng" bạn rất muốn thử với mình dạo này?"}'),
('spicy', '{"en": "Do you prefer it romantic and slow, or rough and passionate?", "vi": "Bạn thích mọi thứ nhẹ nhàng lãng mạn hay mạnh bạo nồng nhiệt hơn?"}'),
('spicy', '{"en": "What is a secret sensitive spot on your body?", "vi": "Đâu là điểm nhạy cảm bí mật trên cơ thể bạn?"}'),
('spicy', '{"en": "How often would your ideal sexual life occur?", "vi": "Tần suất lý tưởng của riêng bạn về chuyện chăn gối là bao nhiêu?"}'),
('spicy', '{"en": "Truth: Have you ever faked an orgasm?", "vi": "Sự thật: Bạn đã bao giờ giả vờ lên đỉnh chưa?"}'),
('spicy', '{"en": "If we were in public, how would you secretly tell me you are horny?", "vi": "Nếu đang ở nơi đông người, bạn làm cách nào để ra hiệu là bạn đang nứng?"}'),
('spicy', '{"en": "What’s the most taboo thing you find sexy?", "vi": "Điều cấm kỵ nào mà bạn nghe lại thấy kích thích?"}'),
('spicy', '{"en": "Dare: Send me the dirtiest text you can think of while sitting next to me.", "vi": "Thử thách: Ngồi cạnh nhau nhưng nhắn cho mình một tin nhắn gợi cảm nhất có thể."}'),
('spicy', '{"en": "What roleplay scenario is highly appealing to you?", "vi": "Kịch bản nhập vai (Roleplay) kiểu nào hấp dẫn bạn?"}'),
('spicy', '{"en": "Morning sex or midnight sex?", "vi": "Chuyện ấy vào buổi sáng mới dậy hay giữa đêm khuya?"}'),
('spicy', '{"en": "Dare: Let me browse your search history for 30 seconds.", "vi": "Thử thách: Giao máy đây, cho kiểm tra lịch sử duyệt web 30 giây."}'),
('spicy', '{"en": "What was the most surprising thing you learned about me in bed?", "vi": "Điều gì ở mình làm bạn ngạc nhiên nhất lúc lên giường?"}'),
('spicy', '{"en": "Would you ever want to involve toys or recorded videos?", "vi": "Bạn có sẵn sàng mang thêm đồ chơi hoặc muốn quay video làm kỉ niệm không?"}'),
('spicy', '{"en": "If you could only touch me with one hand today, where would it go?", "vi": "Nếu hôm nay bạn chỉ được dùng 1 tay để chạm vào người mình, nó sẽ đặt ở đâu?"}'),
('spicy', '{"en": "Dare: Remove one piece of clothing.", "vi": "Thử thách: Cởi một món đồ trên người xuống."}');
